### ISSUE TITLE
saliva crash 

### ISSUE THREAD

**Issue by fgjnfjidfiosqjfkof** [BullyWiiPlaza/JMaster-Duel-Bot#13]
was working well yesterday but today when i run the bot the game instantly crush and i get those text from the bot 
ExternalProcessException{returnValue=0x1, message='2022-11-17 12:52:50.110 (   0.186s) [                ] BotUtilitiesClient.cpp:698    ERR| Process id not found for process name masterduel.exe'}
	at la.I(bk:232)
	at g.I(pn:512)
	at g.I(pn:278)
	at LA.e(ej:789)
	at lpT1.Y(ef:1356)
	at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2000)
	at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2320)
	at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:458)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:374)
	at java.desktop/javax.swing.AbstractButton.setSelected(AbstractButton.java:346)
	at lpT1.I(ef:714)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BullyWiiPlaza** [comment]
Hi, the game has updated, please wait until the bot has been fixed for the latest update `v1.3.2`.

**Comment by BullyWiiPlaza** [comment]
The update is done.

**Comment by fgjnfjidfiosqjfkof** [comment]
thank you so much bro
