### ISSUE TITLE
Error when launching game

### ISSUE THREAD

**Issue by BlueMaxYT** [BullyWiiPlaza/JMaster-Duel-Bot#5]
ExternalProcessException{returnValue=0x1, message='EnumProcessModules() failed: (299) Only part of a ReadProcessMemory or WriteProcessMemory request was completed.'}
	at Eb.c(lm:455)
	at G.c(gf:540)
	at XA.c(cj:39)
	at jA.h(tn:1200)
	at jA.c(tn:749)
	at Oa.b(qd:2047)
	at Oa.m(qd:2230)
	at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2000)
	at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2320)
	at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:458)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:374)
	at java.desktop/javax.swing.AbstractButton.setSelected(AbstractButton.java:346)
	at Oa.M(qd:1140)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I got this error when I launch Master Duel along with JMaster Duel Bot.

**Comment by Anonymous-del** [comment]
I same

**Comment by BullyWiiPlaza** [comment]
Hello, please wait till the bot has been updated to reflect the newest game version.
