### ISSUE TITLE
Crashing while running untapped

### ISSUE THREAD

**Issue by randoomdude** [BullyWiiPlaza/JMaster-Duel-Bot#52]
Game seems to crash after 1 duel if you  have both it and untapped extension running, or won't run untapped unless you start jmbaster bot during coin flip

 Error:
ExternalProcessException{returnValue=0xC0000409, message='The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.'}
	at L.L(lg:419)
	at bB.L(jm:637)
	at bB.j(jm:41)
	at AA.Ja(eh:3218)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BullyWiiPlaza** [comment]
Hello, this other app wasn't developed by us so we don't provide compatibility guarantees. You can try and see if the YGOPRODeck Companion App is working, link: https://ygoprodeck.com/master-duel/companion-app

**Comment by randoomdude** [comment]
I tried the YGOProDeck thing and it seems to have the same issue, that it'll freeze a little after the coin flip in ranked

recorded log, its just literally one minute of turning on game, goingi into ranked and it freezing and crashing
____________________________________

[INFO ] 23:08:19.570 [GUI Thread]: Launching GUI...
[INFO ] 23:08:19.649 [SSL Certificate Trust Manager Installer]: All SSL certificates are now trusted
[INFO ] 23:08:20.465 [GUI Thread]: Configuring frame properties...
[INFO ] 23:08:20.716 [GUI Thread]: Configuring application tabs...
[INFO ] 23:08:20.717 [GUI Thread]: Configuring cheats tabs...
[INFO ] 23:08:20.754 [GUI Thread]: Configuring settings tabs...
[INFO ] 23:08:21.046 [Application Validator]: Performing application validation...
[INFO ] 23:08:22.322 [GUI Thread]: Configuring bot tabs...
[INFO ] 23:08:22.584 [GUI Thread]: Configuring card search tabs...
[INFO ] 23:08:22.593 [GUI Thread]: Configuring donator tabs...
[INFO ] 23:08:22.645 [GUI Thread]: Configuring about tabs...
[INFO ] 23:08:22.657 [GUI Thread]: Configuring process controls tabs...
[INFO ] 23:08:22.687 [Donator Authentication Checker]: Generating license key...
[INFO ] 23:08:24.311 [GUI Thread]: Authenticated successfully...
[INFO ] 23:08:24.439 [Operating System Printer]: Operating system: Microsoft Windows 10 Pro
[INFO ] 23:08:25.274 [Process Interaction Button Availability Setter]: Injecting speed hack...
[INFO ] 23:08:26.202 [Process Interaction Button Availability Setter]: Setting speed hack speed to: 1.0999999999999999x
[ERROR] 23:08:40.459 [Process Interaction Button Availability Setter]: 
lpt6: 2024-03-25 23:08:40.455 (   0.207s) [                ] BotUtilitiesClient.cpp:790    ERR| Failed to find main window handle

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:1086) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:241) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.F(xj:221) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.c(xj:210) ~[qzegLA976qaHaPzioyv1:?]
	at va.j(kg:2987) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:40.517 [Process Interaction Button Availability Setter]: 
lpt6: Finding process by process id: 18292
EnumProcessModules() failed: (299) Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.c(zg:412) ~[qzegLA976qaHaPzioyv1:?]
	at va.j(kg:2870) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:41.536 [Player Latency Reader]: 
lpt6: 2024-03-25 23:08:41.532 (   0.210s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:1086) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:241) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.F(xj:221) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.c(xj:210) ~[qzegLA976qaHaPzioyv1:?]
	at va.Z(kg:3946) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:41.677 [Process Interaction Button Availability Setter]: 
lpt6: Finding process by process name: -1
Process id for process name not found

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.c(zg:412) ~[qzegLA976qaHaPzioyv1:?]
	at va.j(kg:2870) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:42.609 [Deck Tracker Updater]: 
lpt6: 2024-03-25 23:08:42.604 (   0.199s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:1086) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:241) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.F(xj:221) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.c(xj:210) ~[qzegLA976qaHaPzioyv1:?]
	at va.S(kg:900) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:42.849 [Process Interaction Button Availability Setter]: 
lpt6: Finding process by process name: -1
Process id for process name not found

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.c(zg:412) ~[qzegLA976qaHaPzioyv1:?]
	at va.j(kg:2870) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:43.703 [Duel Spy Updater]: 
lpt6: 2024-03-25 23:08:43.699 (   0.206s) [                ] BotUtilitiesClient.cpp:790    ERR| Process id not found for process name masterduel.exe

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:1086) ~[qzegLA976qaHaPzioyv1:?]
	at fb.F(zg:241) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.F(xj:221) ~[qzegLA976qaHaPzioyv1:?]
	at LPt9.c(xj:210) ~[qzegLA976qaHaPzioyv1:?]
	at va.K(kg:2142) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:44.025 [Process Interaction Button Availability Setter]: 
lpt6: Finding process by process name: -1
Process id for process name not found

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.c(zg:412) ~[qzegLA976qaHaPzioyv1:?]
	at va.j(kg:2870) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[ERROR] 23:08:45.201 [Process Interaction Button Availability Setter]: 
lpt6: Finding process by process name: -1
Process id for process name not found

	at Gb.F(am:611) ~[qzegLA976qaHaPzioyv1:?]
	at fb.c(zg:412) ~[qzegLA976qaHaPzioyv1:?]
	at va.j(kg:2870) ~[qzegLA976qaHaPzioyv1:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]

**Comment by BullyWiiPlaza** [comment]
This issue cannot be reproduced with the YGOPRODeck Companion app, it's working fine in Ranked duels, I just tried it. So maybe it's not a conflict between both tools. I encourage you to do more testing if a single tool causes these issues after all for you specifically.

**Comment by DavidZhu1388** [comment]
Hi I am encountering a similar issue where I went to the duel strategy 2 and the first top practice. The game crashed and I cannot restart or quit the "game":

ExternalProcessException{returnValue=0x1, message='Finding process by process id: 217836
EnumProcessModules() failed: (299) Only part of a ReadProcessMemory or WriteProcessMemory request was completed.'}
	at nA.g(nk:324)
	at I.g(fd:309)
	at FA.g(qk:1)
	at P.c(gk:364)
	at P.c(gk:2162)
	at fb.ca(pk:1925)
	at fb.<init>(pk:703)
	at MasterDuelBotClient.g(ah:445)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BullyWiiPlaza** [comment]
> Hi I am encountering a similar issue where I went to the duel strategy 2 and the first top practice. The game crashed and I cannot restart or quit the "game":
> 
> ExternalProcessException{returnValue=0x1, message='Finding process by process id: 217836 EnumProcessModules() failed: (299) Only part of a ReadProcessMemory or WriteProcessMemory request was completed.'} at nA.g(nk:324) at I.g(fd:309) at FA.g(qk:1) at P.c(gk:364) at P.c(gk:2162) at fb.ca(pk:1925) at fb.(pk:703) at MasterDuelBotClient.g(ah:445) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Hello, I played and beat the Duel Strategy 2 first top practice mode manually and it didn't crash at all:
![image](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/7620135/0f0b5253-e381-4327-b5bf-f6ffef95be12)

Can you clarify how you manage to crash? Which settings/options did you turn on in the bot? Maybe send some screenshots. Thanks.

**Comment by BullyWiiPlaza** [comment]
It seems like the issue cannot be reproduced or is no longer relevant so I'm closing this issue.
