### ISSUE TITLE
Game and software errors

### ISSUE THREAD

**Issue by shiqiemo** [BullyWiiPlaza/JMaster-Duel-Bot#62]
When I open the YGO MD and the JMDBot at the same time, the game will flash back and this pop-up will appear. I copied the code here, please give a hand.I have restarted the computer many times before, but nothing has worked out.（Sorry, my English is not very good, this is translated by machine.）

java.io.IOException: Remaining try count exceeded, failed to find function: vuEFV63iutTiNDRcqvnm
	at EA.L(se:195)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:178)
	at EA.L(se:134)
	at lpt7.L(ld:560)
	at YA.I(ll:885)
	at Aa.ba(yl:2350)
	at Aa.<init>(yl:492)
	at MasterDuelBotClient.L(eg:661)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BullyWiiPlaza** [comment]
Hello, there was a game update. Please follow the #announcements channel on the Discord server for updates and news on the bot.

**Comment by shiqiemo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
