### ISSUE TITLE
Crash Code, unknown whats causing it

### ISSUE THREAD

**Issue by Acebeastyt** [BullyWiiPlaza/JMaster-Duel-Bot#64]
java.io.IOException: Remaining try count exceeded, failed to find function: vuEFV63iutTiNDRcqvnm
	at oa.B(bd:46)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:2)
	at oa.B(bd:115)
	at zb.B(uj:382)
	at GB.m(fm:1891)
	at WA.Ca(dk:2743)
	at WA.<init>(dk:295)
	at MasterDuelBotClient.B(rf:584)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BullyWiiPlaza** [comment]
Not every error you get is a problem, you can ignore it, it's a random error that happens when the game didn't respond fast enough or wasn't loaded yet.
