### ISSUE TITLE
Issue on Windows 10 Pro with Live/Evil Twins (★ and ☆)

### ISSUE THREAD

**Issue by randoomdude** [BullyWiiPlaza/JMaster-Duel-Bot#71]
For about a year master duel wasn't working on one very specific account and I didn't really know what was going on, I could play the acccount without Jmaster Duel bot, but when I activated it the game would crash. I tried running it on a laptop running windows 11 and it worked so I just played on that. Recently though I tried running it again, and realized I could play with any other deck that wasn't live twin, so when I narrowed it down I realized it was literally just the cards with the little ☆ in their name that was crashing the game, any idea what is causing this?

**Comment by randoomdude** [comment]
Actually it only crashes in multiplayer, if you run it in solo mode it won't crash

**Comment by BullyWiiPlaza** [comment]
Ah, good catch! Finally we got it narrowed down. Yes, the little ☆ is a unicode character which might throw something off in the code. Unicode support is a nasty issue which is often overlooked when developing. I'll look into it soon.

**Comment by randoomdude** [comment]
it seems like the higher resolution you play it on the more likely the chance that it crashes too maybe? it's always at the beggining of the duel when you draw 5 cards it and says "DUEL", so maybe game is trying to load stuff properly and gets overwhelmed or something

**Comment by randoomdude** [comment]
Game crashed pretty suddenly, with the audio stuttering. Feels like program is becoming more unstable on this computer over time, I feel like uninstalling doesn't reset things very well, also terminate application forcefully almost always says "Failed to terminate the process with process id: 30280" when it didn't before.
------------------
Error report:

java.io.IOException: Remaining try count exceeded, failed to find function: ipBndkd2mmKZ72foCV6I
	at G.h(hn:23)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:145)
	at G.h(hn:13)
	at LpT3.h(in:447)
	at y.h(di:741)
	at y.F(di:658)
	at CA.h(rj:3873)
	at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2000)
	at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2320)
	at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:458)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:374)
	at java.desktop/javax.swing.AbstractButton.setSelected(AbstractButton.java:346)
	at CA.f(rj:897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
